ONLY_PICTURES_ERR=Only Pictures can be added as an Emote
MESSAGE_CANNOT_BE_EMPTY=message cannot be empty
MESSAGE_TOO_LONG=message cannot be longer than {0} characters
MEDIA_DATA_SHOULD_HAVE_A_NAME=a media should have a name
MESSAGE_ANSWERED_DOES_NOT_EXIST=message answered does not exist
ANSWER_MUST_BE_IN_THE_SAME_ROOM=answer must be in the same room of the original message
ROOM_TYPE_CANNOT_BE_CHANGED=You cannot change the type of room. please create a new one.
SERVER_STRUCTURE_WITH_ROOM_THAT_DOES_NOT_EXISTS=The provided server structure has room that does not exist
SERVER_NOT_PUBLIC=This server is not public. You need an invitation.
NO_VALID_INVITATION=You must have a valid invitation to join this server.
USER_NOT_FOUND=user not found
USER_LOGIN_INVALID=invalid username
USER_WITH_NO_VALID_INVITATION=You must have a valid invitation to signup.
USER_PASSWORD_INVALID=invalid password format
USER_PASSWORD_WRONG=wrong password
USER_PASSWORD_WRONG_CONFIRMATION=new password and confirmation should be identical
RISK_MEMBERSHIP_ERROR=You do not have one of the correct risks : {0}
RISK_ABOVE_ERROR=Tou cannot update a risk above you awn priority
UNAUTHORIZED_TITLE=Access denied
UNAUTHORIZED_MESSAGE=You do not have permission to access this resource.
FORBIDDEN_TITLE=Access forbidden
FORBIDDEN_MESSAGE=You do not have permission to access this resource.
NOT_FOUND={0} with id {1} does not exist
NOT_FOUND_TITLE=Resource not found
NOT_FOUND_MESSAGE=This url is in another castle.
METHOD_NOT_ALLOWED_TITLE=Method not allowed
METHOD_NOT_ALLOWED_MESSAGE=this method is not allowed
INTERNAL_SERVER_ERROR_TITLE=Internal Server Error
INTERNAL_SERVER_ERROR_MESSAGE=Something went wrong on our side. Please try again later or contact support if the problem persists.
DOCUMENTATION_API_LINK=See the API documentation
